// Generated by CoffeeScript 2.5.1
(function() {
  var holder;

  holder = document.createElement('div');

  holder.className = 'modal-holder';

  holder.innerHTML += require('./modal.pug')();

  document.body.appendChild(holder);

  module.exports = {
    setContent: function(content) {},
    show: function(content, controller) {
      return new Promise(function(resolve, reject) {
        var modalWindow;
        modalWindow = document.querySelector('.modal-window');
        modalWindow.innerHTML = content;
        if (typeof controller === "function") {
          controller(resolve, reject);
        }
        return document.body.className = document.body.className.replace(/ *modal-out/, '') + ' modal-out';
      });
    },
    hide: function() {
      var modalWindow;
      document.body.className = document.body.className.replace(/ *modal-out/, '');
      modalWindow = document.querySelector('.modal-window');
      return setTimeout(function() {
        return modalWindow.innerHTML = '';
      }, 400);
    }
  };

}).call(this);
