// Generated by CoffeeScript 2.5.1
(function() {
  var GraphFollower;

  GraphFollower = function(audio) {
    var constantNode, duration, graph, lastTime, multiplier, offset, startTime;
    graph = null;
    constantNode = null;
    duration = null;
    multiplier = 1;
    offset = 0;
    startTime = 0;
    lastTime = 0;
    return {
      fromGraph: function(_graph, _duration, _multiplier, _offset, time) {
        graph = _graph;
        duration = _duration;
        multiplier = multiplier || _multiplier;
        offset = offset || _offset || 0;
        constantNode = audio.createConstantSource();
        constantNode.offset.value = offset;
        constantNode.start();
        startTime = time || audio.currentTime;
        lastTime = startTime;
        return {
          connect: function(what) {
            return constantNode.connect(what);
          },
          start: function(time) {
            startTime = time || audio.currentTime;
            return lastTime = startTime;
          },
          update: function() {
            var nextTime, val, x;
            nextTime = audio.currentTime - lastTime;
            nextTime = Math.max(nextTime, 1 / 120);
            lastTime = audio.currentTime;
            x = ((audio.currentTime - startTime) % duration) / duration;
            val = graph.getValue(x);
            return constantNode.offset.setTargetAtTime((val * multiplier) + offset, audio.currentTime + nextTime, 0.5);
          }
        };
      }
    };
  };

  window.GraphFollower = GraphFollower;

  module.exports = GraphFollower;

}).call(this);
