// Generated by CoffeeScript 2.5.1
(function() {
  window.ogid = function(radix, rnd) {
    return parseInt((new Date().valueOf() - new Date(2020, 0, 1).valueOf()).toString().concat(Math.floor(Math.random() * (99999 || rnd))).split('').reverse().join('')).toString(radix || 36);
  };

  module.exports = window.ogid;

}).call(this);
