// Generated by CoffeeScript 2.5.1
(function() {
  window.$ = function(selector, parent) {
    return (parent || document).querySelector(selector);
  };

  window.$A = function(selector, parent) {
    return (parent || document).querySelectorAll(selector);
  };

  module.exports = 'tools';

}).call(this);
