// Generated by CoffeeScript 2.5.1
(function() {
  window.Track = function(opts) {
    var gain;
    gain = opts.audio.createGain();
    return {
      id: ogid(),
      pointer: 0,
      wrap: true,
      steps: opts.steps || 4,
      lastTime: -1,
      tempo: opts.tempo,
      current: {},
      notes: [],
      addNote: function(note) {
        var pointerNote;
        pointerNote = this.notes[this.pointer];
        if (pointerNote && pointerNote.time > note.time) {
          this.pointer++;
        }
        note.track = this;
        note.id = ogid();
        this.notes.push(note);
        this.notes.sort(function(a, b) {
          if (a.time < b.time) {
            return -1;
          } else {
            return 1;
          }
        });
        return note;
      },
      removeNote: function(note) {
        var pointerNote;
        pointerNote = this.notes[this.pointer];
        if (pointerNote && pointerNote.time < note.time) {
          this.pointer--;
        }
        return this.notes.splice(this.notes.indexOf(note), 1);
      },
      destination: gain,
      connect: function(thing) {
        return gain.connect(thing);
      }
    };
  };

  module.exports = window.Track;

}).call(this);
