// Generated by CoffeeScript 2.5.1
(function() {
  var ffmpeg, fs, glob, oggFromMkv, path, pathToFfmpeg;

  pathToFfmpeg = require('ffmpeg-static');

  ffmpeg = require('fluent-ffmpeg');

  glob = require('glob');

  path = require('path');

  fs = require('fs-extra');

  ffmpeg.setFfmpegPath(pathToFfmpeg);

  console.log(pathToFfmpeg);

  oggFromMkv = function(input, output) {
    return new Promise(function(resolve, reject) {
      return ffmpeg(input).noVideo().audioCodec('libvorbis').audioBitrate(128).output(output).on('end', function() {
        return resolve();
      }).run();
    });
  };

  module.exports = {
    convertVideoFolder: function() {
      return new Promise(function(resolve, reject) {
        return glob('C://Users/lewis/Videos/*.mkv', async function(err, files) {
          var file, i, len, parsed;
          for (i = 0, len = files.length; i < len; i++) {
            file = files[i];
            parsed = path.parse(file);
            await oggFromMkv(file, path.join(parsed.dir, parsed.name + '.ogg'));
            await fs.unlink(file);
          }
          return resolve();
        });
      });
    }
  };

}).call(this);
