// Generated by CoffeeScript 2.5.1
(function() {
  document.body.innerHTML += require('./alert.pug')();

  module.exports = {
    show: function(message) {
      var alert;
      document.querySelector('.alert .message').innerHTML = message;
      alert = document.querySelector('.alert');
      alert.className = alert.className.replace(/ *hidden/, '') + ' visible';
      return setTimeout(function() {
        return alert.className = alert.className.replace(/ *visible/, '') + ' hidden';
      }, 3000);
    }
  };

}).call(this);
