// Generated by CoffeeScript 2.5.1
(function() {
  var ipcRenderer;

  ({ipcRenderer} = require('electron'));

  console.log('hey from renderer');

  setTimeout(function() {
    return ProjectManager.init();
  }, 10);

  ipcRenderer.on('newProject', function() {
    return ProjectManager.new();
  });

  ipcRenderer.on('loadProject', function(win, data) {
    console.log('load project', data, ProjectManager);
    return ProjectManager.loadZip(data);
  });

  ipcRenderer.on('saveProject', function() {
    return ProjectManager.doZip();
  });

  ipcRenderer.on('rendered', function(win, data) {
    return ProjectManager.onRendered(data);
  });

  ipcRenderer.on('show', function(win, data) {
    return ProjectManager.setState(data.state);
  });

  ProjectManager.setRenderFn(function(b64, waveforms, position, nosmps) {
    return ipcRenderer.send('startRender', {
      b64: b64,
      waveforms: waveforms,
      position: position,
      nosmps: nosmps
    });
  });

}).call(this);
